name: Curseforge Release

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      ZIP_FILE_NAME: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Generate Zip file
        run: |

          # Get today's date in YYYY-MM-DD format
          DATE=$(date +%F)
        
          # Replace spaces in the value from action variable with underscores
          VALUE_FROM_VARIABLE=$(echo "${{ github.event_name }}" | tr ' ' '_')
        
          # Combine date and value to form the zip file name
          DISPLAY_NAME="LibMVC-1.0-${DATE}" 
          ZIP_FILE_NAME="$DISPLAY_NAME.zip"
          
          zip -r "$ZIP_FILE_NAME" * -x README.md
          echo "File name: $ZIP_FILE_NAME"

          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: Upload to Curseforge API
        run: |
          API_URL="https://wow.curseforge.com/api/projects/${{ vars.CURSEFORGE_PROJECT_ID }}/upload-file"
          FILE_PARAM="file=$ZIP_FILE_NAME"
          echo "File param 1: $FILE_PARAM"
          FILE_PARAM="$ZIP_FILE_NAME"
          echo "File param 2: $FILE_PARAM"
          FILE_PARAM="file=@$ZIP_FILE_NAME"
          echo "File param 3: $FILE_PARAM"
          
        
          curl -L -X POST \
          -H "x-api-token: ${{ secrets.CURSEFORGE_API_TOKEN }}" \
          -F "metadata={\"displayName\": \"$DISPLAY_NAME\", \"gameVersions\": [10215], \"releaseType\": \"release\", \"changelog\": \"First commit via GitHub\"}"  \
          -F "$FILE_PARAM" \
          "$API_URL"
