name: Curseforge Release

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Job 1: build the zip file
  build-zip-file:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # specify the environment variables used by the packager, matching the secrets from the project on GitHub
    env:
      PROJECT_NAME: "LibMVC-1.0"
      CURSEFORGE_API_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
      ZIP_FILE_NAME: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Generate Zip file
        run: |

          # Get today's date in YYYY-MM-DD format
          DATE=$(date +%F)
        
          # Replace spaces in the value from action variable with underscores
          VALUE_FROM_VARIABLE=$(echo "${{ github.event_name }}" | tr ' ' '_')
        
          # Combine date and value to form the zip file name
          DISPLAY_NAME="$PROJECT_NAME ${DATE}" 
          ZIP_FILE_NAME="$DISPLAY_NAME.zip"
          
          zip -r "$ZIP_FILE_NAME" * -x README.md
          echo "File name: $ZIP_FILE_NAME"

          # Set as environment variable for the next step
          echo "DISPLAY_NAME=$DISPLAY_NAME" >> $GITHUB_ENV
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV
          echo "CHANGELOG=\"First commit via GitHub\"" >> $GITHUB_ENV
          echo "CURSEFORGE_PROJECT_ID=${{ vars.CURSEFORGE_PROJECT_ID }}" >> $GITHUB_ENV

  # Job 2: Send the zip to the private repo
  trigger-curse-upload:
    needs: build-zip-file
    uses: Thaoky/CurseForgeUploader/.github/workflows/main.yml@main
    with:
      zip-file-path: $ZIP_FILE_NAME
      addon-display-name: $DISPLAY_NAME
      change-log: $env.CHANGELOG
      curse-project-id: $CURSEFORGE_PROJECT_ID
    secrets:
      envPAT: ${{ secrets.envPAT }}
      
